spigot:
  container_name: emeraldquest
  environment:
    - EMERLADQUEST_ENV=development
    - DENOMINATION_NAME=Ems
    - LAND_PRICE=200
    - MIN_LOOT=3
    - MAX_LOOT=100
    - LOOTIPLIER=50
    - ADMIN_UUID=CHANGEME
    - SET_PvP=true
  build: .
  volumes:
    - "./build/libs/:/spigot/plugins"
    - ".:/emeraldquest"
  ports:
    - "25565:25565"
  links:
    - redis
redis:
  image: redis
