spigot:
  container_name: emeraldquest
  environment:
    - EMERLADQUEST_ENV=development
    - DENOMINATION_NAME=Ems
    - LAND_PRICE=200
    - MIN_LOOT=3
    - MAX_LOOT=100
    - LOOTIPLIER=50
    - ADMIN_UUID=CHANGEME
    - SET_PvP=true
  build: .
  volumes:
    - "/EmeraldQuest/spigot/world:/spigot/world"
    - "/EmeraldQuest/spigot/world_nether:/spigot/world_nether"
    - "/EmeraldQuest/spigot/world_the_end:/spigot/world_the_end"
  ports:
    - "25564:25564"
  links:
    - redis
redis:
  image: redis
  volumes:
    - "/EmeraldQuest/redis:/data/"
